### ISSUE TITLE
Domain Model

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#106]
Present the domain model, and describe why is has been designed the way it has, and what purpose it serves in our project.

**Comment by martin-vlacil** [comment]
Added a source, fixed some spelling, added one line:



![Image](https://user-images.githubusercontent.com/75024378/211288560-9b0271f5-f719-4a73-a94c-1790e51be84a.png)

**Comment by mirodmarinov** [comment]
We need to be careful with similar statements because the domain model, at least at that stage, has little to do with implementation/development yet.

**Comment by mette-thorhauge** [comment]
@mirodmarinov I have suggested a renaming, please review it and see if it better explains the intention of the domain model

**Comment by mirodmarinov** [comment]
Accepted :)
