### ISSUE TITLE
Proposed Architecture

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#107]
Write about the Architecture diagram that has been created. 

Make sure to clarify that the arrows in the diagram indicate which entitity initates the communication between the two entities connected by the arrows.

It should also be mentioned that the two sections indicate which parts of the diagram we will be developing.

**Comment by mirodmarinov** [comment]
Wrote about it and made a diagram. pls read

**Comment by WrexBG** [comment]
I read it, we mention some stuff for the first time that we define later on but overall it explains the proposed architecture.
Would be nice if someone else also looks at it since its a big chapter.

**Comment by mette-thorhauge** [comment]
I have looked at it and added some comments. Most of them have since been resolved, so I don't know if we can close the issue and address the remaining comments at walkthrough
