### ISSUE TITLE
Design Patterns

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#108]
Write briefly about the purpose of design patterns, and then mention the main points:

- [x]  Dependency Injection: Write about what dependency injection is
- [x] Factory Pattern: Write about what the factory pattern is, and how we use it
- [x] DTO Pattern: Write about what the DTO pattern is, and how we use it

For these chapters, please use screenshots of our own code anywhere relevant.

**Comment by mirodmarinov** [comment]
Added 2 more patterns:

- [ ] DAO Pattern - currently missing only screenshots
- [ ] Publish-Subscribe pattern - covering the theory behind rabbitMQ

**Comment by WrexBG** [comment]
Looks good.
