### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#109]
Write about briefly about what database design is and why it is important. Then introduce the relational DB schema and describe how it has been developed. Make sure to mention the different normal forms and the reasons behind the denormalization it has gone through after reaching normal form 3.5

**Comment by mette-thorhauge** [comment]
Some text has already been written about the importance of database design, as well as some details about different database types. I do not know who wrote it though.

**Comment by mirodmarinov** [comment]
Add brief description of Normal forms

**Comment by WrexBG** [comment]
Wrote about choice of database, relational DB schema and normal forms

![Image](https://user-images.githubusercontent.com/40688355/210516854-9b751e87-10fe-422c-954e-a6941c4aa980.png)

**Comment by martin-vlacil** [comment]
looked through it, added a comment about sourcing to some definitions, otherwise looks good to me (y)

**Comment by WrexBG** [comment]
answered
in short: sure, if we find a reference

**Comment by mette-thorhauge** [comment]
I have now read it, and made some minor suggestions to change. I would love for @WrexBG to check whether these would change it to still support what he means by what was originally written, or if they change it too much.

**Comment by WrexBG** [comment]
Approved changes, added a reference and some more description on keys from the book.
