### ISSUE TITLE
Architecture Types

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#110]
Write about architecture types and why we work with them

This chapter contains 2 sub-headers:

1. Monolithic architecture 
2. Service-oriented architecture/Microservices

Briefly describe what they are, as well as their main advantages and disadvantages. Within the microservice chapter make sure to get into cloud computing as well as containerization

**Comment by mette-thorhauge** [comment]
I have now finished writing about architecture types, so I am moving it into implement done. I added a general introduction to Architecture while writing this. 
The sections I have added are:
8 Architecture and Design
8.1 Architecture types
8.1.1 Monolithic architecture
8.1.2 Service-oriented Architecture/ microservices

**Comment by WrexBG** [comment]
Well explained 👍 
Would love for someone else to look at it as well

**Comment by mirodmarinov** [comment]
I added a new chapter:

- [ ] Client-Server model - missing a bit of content

SO please look at it fi you can

**Comment by mirodmarinov** [comment]
We need to agree of the definition of architecture choice is not mutually exclusive and can be overlapping/use multiple?

**Comment by mette-thorhauge** [comment]
I have changed the introduction of the chapter to hopefully clarify, I would love your feedback on it @mirodmarinov 😊

**Comment by mirodmarinov** [comment]
Looks good :)
