### ISSUE TITLE
aFRR Service

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#111]
Describe the implementation of our web service - the aFRR service. Make sure to touch upon:

- [x] The Message consumer
- [x] The overall architecture of the solution
- [x] DataAccess SQL transactions
- [x] WebAPi @martin-vlacil

**Comment by martin-vlacil** [comment]
Wrote a bit about JSON format, not sure if its perfect, needs validadtion

![Image](https://user-images.githubusercontent.com/75024378/212058495-32eab7e4-5242-448d-bb1c-e5d5e6f00465.png)

**Comment by martin-vlacil** [comment]
There wasnt much to write about the api as it only stores stuff in database and takes it back soo


![Image](https://user-images.githubusercontent.com/75024378/212089094-65d3490e-aded-40f7-9640-a51df5e97f45.png)

**Comment by mirodmarinov** [comment]
Wrote about the general service structure as well as the consumer. Maybe a paragraph more in the consumer is worth it

**Comment by martin-vlacil** [comment]
changed the header and added a small paragraph to the data access layer

![Image](https://user-images.githubusercontent.com/75024378/212093948-df24c4b4-acd2-4d4d-b1cf-80e340bc45a6.png)

**Comment by mette-thorhauge** [comment]
I have finished reading it, and I have added my input in the form of comments. Overall, the chapter seems fine to me.
