### ISSUE TITLE
Prioritization Service

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#112]
Write about the Prioritization Service and it's purpose within our architecture, make sure to mention:

- [x] Priotization Logic #125

**Comment by WrexBG** [comment]
Added description of the service itself and its task


![Image](https://user-images.githubusercontent.com/40688355/211784590-d633393a-89e0-457b-8f79-88b175ad90bb.png)

**Comment by mette-thorhauge** [comment]
I have reviewed it and I am unassigning myself

**Comment by martin-vlacil** [comment]
same, looks good to me

**Comment by zythaarcz** [comment]
I approve
