### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#114]

**Comment by WrexBG** [comment]
Wrote about the ORM Choice and the BaseDataAccess


![Image](https://user-images.githubusercontent.com/40688355/209820635-b8684911-622a-4353-a45c-1580a6a45930.png)
![Image](https://user-images.githubusercontent.com/40688355/209820631-b9cce918-248b-4659-a7d1-ee32a22f5544.png)

**Comment by WrexBG** [comment]
Added a small conclusion at the end

**Comment by mette-thorhauge** [comment]
I have finished validating this chapter, only one comment remains, however, it is dependent on another task. Therefore, a comment has been added in the relevant task:  #95
