### ISSUE TITLE
aFRR Service Data Access for regulation prioritization

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#117]
Make a data access to call the prioritization web API and request a regulation priority.

**Comment by mette-thorhauge** [comment]
The method that calls the API needs:

- [ ] API URL which is stored in the configuration file along with other connectionstrings
- [ ] Prepare SignalDTOs for JSON body
- [ ] In the data access class:
      - [ ] Extract connection string and store in field
      - [ ] A new object of type HttpClient
      - [ ] Call the GetAsync method
