### ISSUE TITLE
Literary Search/Delimitation

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#121]

**Comment by mirodmarinov** [comment]
Wrote 2 subchapters:

- [ ] Why are we not including literary search - still worth maybe including a literary search template in the appendices.
- [ ] Why are we covering only part of the aFRR flow.

**Comment by martin-vlacil** [comment]
looks gut

**Comment by WrexBG** [comment]
should this be closed?
