### ISSUE TITLE
Prioritization Model

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#125]

**Comment by mirodmarinov** [comment]
maybe this is the current implementation of the prioritization model?

**Comment by WrexBG** [comment]
Description of the current implementation of the basic model


![Image](https://user-images.githubusercontent.com/40688355/211784486-22ca6b0a-205e-4028-a9d7-b9a5a752cf48.png)

**Comment by mette-thorhauge** [comment]
I have finished reviewing it, and so I am unassigning myself.
