### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mette-thorhauge** [diversiwaver/aFRR-NET#127]
Write about possible necessary security measures, while doing this, touch upon the theory and possible implementation of:

- [x] Authentication
- [x] Authorization

**Comment by mirodmarinov** [comment]
Finished both, added some content for JWT, XSS, CSRF

**Comment by mette-thorhauge** [comment]
I have read it and it looks okay to me. My only note is, that I am not sure whether the wording should make it clearer how we would implement it in our project if we had the time.

**Comment by martin-vlacil** [comment]
Looks understandable, quite long for a future improvement stuff tbh, and would be nice to see it better connect to how we would implement in the project

**Comment by WrexBG** [comment]
separated the possible attacks to API and website


![Image](https://user-images.githubusercontent.com/40688355/211815425-bf001bba-d52b-4955-8217-d8c7750141e8.png)
