### ISSUE TITLE
Add content to Consumer

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#133]

**Comment by WrexBG** [comment]
- [ ] Convert TSOSignal to SignalDTO
- [ ] Send SignalDTO to Prioritization DataAccess 
- [ ] Send what Prioritization DataAccess returns to RemoveControlDataAccess

**Comment by WrexBG** [comment]
![Image](https://user-images.githubusercontent.com/40688355/211051595-b7480f90-8995-4503-9714-09e12d4e6563.png)
