### ISSUE TITLE
Future Improvements: Logging

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#148]
Different logs should be used in development and production as we dont want too much normally but it can be good for debugging. It affects performance so it can be good to set log levels.
This however, can damage the performance since logs lower than the current log level don't do anything but are still being called and can allocate memory, which leads to the GC being called more often and thus the application being idle for more time
based off of: https://www.youtube.com/watch?v=bnVfrd3lRv8

**Comment by martin-vlacil** [comment]
Read and changed one line regarding non-functional requirements


![Image](https://user-images.githubusercontent.com/75024378/211577290-6a48d246-11d5-44f6-9db4-d50751adccb0.png)

**Comment by mette-thorhauge** [comment]
I have read it, and I approve everything except the last sentence, which I think contains a typo or something of the sorts. I would love the original writer to check it. Also, the youtube links at the top should be moved right? I am not sure I understand what they are doing there.

**Comment by mette-thorhauge** [comment]
Sentence has been fixed and the issue will now be closed
