### ISSUE TITLE
Future Improvements: Prioritization model

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#151]
Will talk about the following:

- [x] The ideal situation where each asset gets a prioritization score based on a bunch of factors
- [x] Level 2: dynamic programming and Graph theory
- [x] Level 3: Talk about unsupervised machine learning

**Comment by mirodmarinov** [comment]
I mention random tools and technologies and I don't want to "sink our ship" so feel free to remove any of them.

**Comment by mirodmarinov** [comment]
Everything looks, good, fixed.

**Comment by WrexBG** [comment]
Added some possible factors by which the model can be improved

**Comment by zythaarcz** [comment]
I like it, Picasso

**Comment by martin-vlacil** [comment]
i cheacked it, i would like to talk about whether the "graph" chapter is necessary, quite complex and im not sure if i want to be asked about it

**Comment by martin-vlacil** [comment]
![Image](https://user-images.githubusercontent.com/75024378/212100236-82b6cd32-f214-4a08-95cd-de8715e89750.png)
