### ISSUE TITLE
9.4.3. Transactions in SQL

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#153]

**Comment by martin-vlacil** [comment]
![Image](https://user-images.githubusercontent.com/75024378/211801009-5514be18-a605-43b8-9081-cae2bd12008e.png)

wrote this chapter, added a small paragraph about isolation levels :)

**Comment by mette-thorhauge** [comment]
I have read it and addressed the things I didn't agree with. I don't know if anyone else needs to also validate it but I think we should discuss where this chapter should be placed^^

**Comment by mirodmarinov** [comment]
I rewrote the beginning of the chapter

**Comment by WrexBG** [comment]
Looks great
