### ISSUE TITLE
Explain why we denormalize into BidSignalMember table

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#154]

**Comment by martin-vlacil** [comment]
added a small paragraph to better defend our member table

![Image](https://user-images.githubusercontent.com/75024378/212014839-16cc9662-9ac5-4344-bcb7-eef5ca2b9e7c.png)

**Comment by WrexBG** [comment]
Changed a bunch of We's and Our's, otherwise it's good
can you check if I didn't change the meaning of anything?
