### ISSUE TITLE
REST and HTTP/IP

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#157]
Inside Implementation -> aFRR service -> web API

**Comment by mirodmarinov** [comment]
Talked about:

- [x] OSI model, thanks to thomas
- [x] TCP-IP model

**Comment by WrexBG** [comment]
Looks good
Only here it feels a bit disconnected, maybe its because I dont understand what IP is or what part it takes in the model but it just randomly start talking about it.


![Image](https://user-images.githubusercontent.com/40688355/212083593-511defe6-be6e-4cb5-9612-013767d14bf3.png)

**Comment by mirodmarinov** [comment]
I used fancy word, fixed now

**Comment by WrexBG** [comment]
Ah oke =)
