### ISSUE TITLE
Function & Non-Function Requirements & FURPS

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#20]
Write about them in the Quality Managment Chapter
Part of Software requirements
- [x] Functional Requirements
- [x] Non-Functional Requirements
~~FURPS+~~

**Comment by mette-thorhauge** [comment]
I have finished reading through the chapter. Any minor changes or correctios have been done as I went along, and comments have been added to the things we need to discuss as a group, either while looking through the report next week, or before closing this issue, depending on what people prefer? @diversiwaver/team-1
