### ISSUE TITLE
Write Chapter: Implementation

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#31]
- [x] #150
- [x] #108
- [x]  #109 
- [x] #111
- [x] #112 
- [x] #152
- [x] #146

This task does not in itself count towards our WIP limit, since it is tracked in sub-tasks.

**Comment by WrexBG** [comment]
Finished the ORM Chapter
it's currently 10.1 and 10.1.1


![Image](https://user-images.githubusercontent.com/40688355/207864218-658d7ecb-e365-4b58-bdfd-4e5beb8032de.png)

**Comment by zythaarcz** [comment]
9.4.1 and 9.4.2 chapters have short description for RabbitMQ and its alternatives

**Comment by mirodmarinov** [comment]
Added chapter on Grafana and Monitoring

**Comment by mette-thorhauge** [comment]
Should we add a chapter about our mock-services?

**Comment by mirodmarinov** [comment]
I wrote the description of this chapter too
