### ISSUE TITLE
Update Kanban Flow Diagram

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#32]
Add more description for each section based on the Definition of Workflow (DoW) draft in the report

https://www.figma.com/file/i0wvsE3ZA6uhVOTPs2Fsxd/Kanban-Flow?node-id=0%3A1&t=IdKL1MhxcUYGHvzi-0

**Comment by WrexBG** [comment]
Review the changes thoroughly and decide if we really want to do some steps like that. Or if something is missing in there


![Image](https://user-images.githubusercontent.com/40688355/203068919-47242f31-f803-4315-849f-d877ba4ed6df.png)

**Comment by mirodmarinov** [comment]
added a bulletpoint to validate - done and fixed spelling
