### ISSUE TITLE
1. Introduction Chapter

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#4]
* ~~- [ ] Chapter Description~~ moved to #24 
- [x] 1.1 Domain introduction
- [x] 1.2 Company Description
- [x] 1.3 Problem Area
  - [x] 1.3.1 and 2.3.2 Descriptions
  - [x]  1.3.3 Problem Statement
- [x] 1.4 Goals & Ambitions
  - [x] 1.4.1 Company Ambitions
~~- [ ] 1.4.2 Project Goals~~ moved to #25

**Comment by WrexBG** [comment]
Q(^-^Q)
