### ISSUE TITLE
Code Standards

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#44]
Agree and write Code Standards

**Comment by martin-vlacil** [comment]
It is mostly copy paste from 3rd semester but there are new things decided, so go read and see if you agree with what has been set

**Comment by WrexBG** [comment]
https://ucndk.sharepoint.com/:w:/r/sites/Refridgiwaver/_layouts/15/Doc.aspx?action=editNew&sourcedoc=%7B67a74e03-5bf5-427b-8085-b811d78859ed%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1669968844247&web=1
