### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#46]
Decide on architecture & architecture diagram

**Comment by WrexBG** [comment]
https://www.figma.com/file/k3bsKz9Y2G8l2z0FD4D0iY/System-Development-Artifacts?node-id=0%3A1&t=dt7nUQc0CgY8Sq1p-0

**Comment by mette-thorhauge** [comment]
I have reviewed, and overall I think it looks great. However, there is one unresolved comment regarding the DBs that I think should be adressed before we close this issue. So I would love for us to resolve it as a group, or with the original creator, which I think is @WrexBG or @mirodmarinov

**Comment by WrexBG** [comment]
It will need some reorganizing based on some feedback from Miro

**Comment by mette-thorhauge** [comment]
The remaining changes have been moved to a new task, that will be worked on from here on out.
