### ISSUE TITLE
Update Domain Model

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#47]
Update the domain model based on Jakob's feedback from https://ucndk.sharepoint.com/:w:/r/sites/Refridgiwaver/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B36363fc6-ef34-440a-b50e-2909c371d16b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

Domain Model: https://www.figma.com/file/k3bsKz9Y2G8l2z0FD4D0iY/System-Development-Artifacts?node-id=0%3A1&t=dt7nUQc0CgY8Sq1p-0

**Comment by WrexBG** [comment]
Added composite aggregation, multiplicity and changed NET Employee and Authorized Employee and removed its credentials attribute
Together with @martin-vlacil & @zythaarcz 


![Image](https://user-images.githubusercontent.com/40688355/205294911-24e9a66e-1c1c-4f37-8598-90c13e47b957.png)

**Comment by mette-thorhauge** [comment]
Relations and multiplicities have been updated and approved by the whole group
