### ISSUE TITLE
Write about the coal plants in introduction

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#55]
Documents are uploaded to teams.

**Comment by mirodmarinov** [comment]
Website references missing - remind me to gib

**Comment by mette-thorhauge** [comment]
I used this website https://beyond-coal.eu/europes-coal-exit/ as provided by Miro. I have taken the liberty of closing the issue, since it simply contains:

- [ ] Adding the website to our reference list
- [ ] Rewrite the two places in the report to include the specified year
