### ISSUE TITLE
Create a mock RabbitMQ Sending service

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#66]
- [x] Create new project
- [x] Add a logger
- [x] Add XML conversion classes
- [x] Add dummy consumer class
- [x] test it by making it listen to the RabbitMQ and consume the queue

**Comment by mirodmarinov** [comment]
Added a new repo

**Comment by mirodmarinov** [comment]
Needs Pull request approval

**Comment by mette-thorhauge** [comment]
@WrexBG and I have now reviewed the PR and commented our suggested changes.
