### ISSUE TITLE
Describe RabbitMQ setup

### ISSUE THREAD

**Issue by mirodmarinov** [diversiwaver/aFRR-NET#67]
**Done:** Writing a brief introduction to MessageQueues, RabbitMQ and its alternatives

**TODO:** Write about the actual implementation when we have some

**Comment by zythaarcz** [comment]
![Image](https://user-images.githubusercontent.com/73475202/208109242-d0145619-4501-4f06-9859-68d23c7f86fd.png)

I wrote a short paragraph about Message queues in general as well as about RabbitMQ. I think it is good enough for now, but I would add more after we actually implement it

**Comment by mirodmarinov** [comment]
Add:

- [ ] Screenshots
- [ ] Update the paragraph as it was written before the queue was implemented

**Comment by WrexBG** [comment]
Looks good
