### ISSUE TITLE
Add screenshot of github repository

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#71]
![Image](https://user-images.githubusercontent.com/75024378/207263663-555afab4-ec97-4d8a-99b8-060150e21eee.png)

**Comment by martin-vlacil** [comment]
added two screenshots, i think leaving both is okay, but if anyone thinks there are too many


![Image](https://user-images.githubusercontent.com/75024378/211752287-63a5876a-5d71-4ac9-9489-33d42988914f.png)

**Comment by martin-vlacil** [comment]
if too many you can change it, im fine with both being there

**Comment by mette-thorhauge** [comment]
I have validated it.
