### ISSUE TITLE
Add definition to Code Review chapter

### ISSUE THREAD

**Issue by martin-vlacil** [diversiwaver/aFRR-NET#72]

**Comment by WrexBG** [comment]
I feel like we agreed that not everyone is required to review the code. It's everyone's responsibility to be familiar with what's going on but for validation 1 to 2 people should be enough in most cases.
I've changed it to this:


![Image](https://user-images.githubusercontent.com/40688355/207314251-0cfa6aa4-0184-46bd-922e-5089845ea673.png)

What do you think @martin-vlacil
