### ISSUE TITLE
Reorganize Architecture Diagram

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#75]
Change how the Architecture Diagram looks in figma

https://www.figma.com/file/k3bsKz9Y2G8l2z0FD4D0iY/System-Development-Artifacts?node-id=0%3A1&t=sk26sAvxg65yUKps-0

- [x] Reorganize the placement of the different elements into external and internal elements
- [x] Rethink the arrows and their meaning
- [x] ~~Add communication protocols~~

**Comment by mette-thorhauge** [comment]
The placement has been changed, however the arrows still need to be clarified.

**Comment by mette-thorhauge** [comment]
@WrexBG and I have finished reevaluating this diagram. Based on a group discussion it has been decided that:

- The arrows represent the flow of data requests/communication initiation.
- The communication protocols will not be included in the diagram
