### ISSUE TITLE
Update Domain Model Association

### ISSUE THREAD

**Issue by WrexBG** [diversiwaver/aFRR-NET#93]
Based on Jakob's feedback
https://www.figma.com/file/k3bsKz9Y2G8l2z0FD4D0iY/System-Development-Artifacts?node-id=0%3A1&t=Ao2RR4kGaW0b2vPe-0

**Comment by WrexBG** [comment]
Changed them to this but I'm never sure when to use which association, or which way the array should face


![Image](https://user-images.githubusercontent.com/40688355/208625878-d71ac56c-3963-4948-a365-ad5e00dd9eda.png)

**Comment by mette-thorhauge** [comment]
I have reviewed and validated the changes based on conversations with @WrexBG who made them😊 I am now closing this issue
